#docker-compose.yml
#https://codigofacilito.com/videos/introduccion-96456894-edd1-43ed-932a-3ccc2d370c3f
#https://stackoverflow.com/questions/63547392/traefik-2-2-docker-websocket-ws-not-working
# TRAEFIK

version: '3'

# Services
services:
    proxy:
        image: traefik:v2.1
        container_name: proxy
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"       # traefik dashboard
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.yml:/traefik.yml
            - ./traefik.log:/traefik.log

    nginx:
        image: nginx
        container_name: nginx
        labels:
            - "environment=dev"
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`nginx.ucssfcec.work`)"

    web-0:
        image: acaty/ucssfcec:1.0.1
        container_name: nginx-ucssfcec
        restart: always
        labels:
            - "environment=production"
            - "traefik.enable=true"
            - "traefik.http.routers.web-0.rule=Host(`ucssfcec.work`)"
        volumes:
            - ~/code/ucssfcec:/usr/share/nginx/html:rw
            - ./dockerfiles/sites-available/ucssfcec.work:/etc/nginx/sites-available/default
            - ~/code/mysql:/var/lib/mysql:rw

    web-1:
        image: acaty/firma:1.0.2
        # build:
        #   context: ./dockerfiles/nginx-php
        #   dockerfile: Dockerfile
        container_name: nginx-firma
        restart: always
        labels:
            - "environment=production"
            - "traefik.enable=true"
            - "traefik.http.routers.web-1.rule=Host(`firma.ucssfcec.work`)"
        volumes:
            - ~/code/firma:/usr/share/nginx/html:rw
            - ./dockerfiles/sites-available/firma.work:/etc/nginx/sites-available/default
            - ~/code/mysql:/var/lib/mysql:rw

    web-2:
        image: acaty/call:1.0.0
        # image: api/nginx-php
        # image: api-websockets/app:latest
        # build:
        #   context: ./dockerfiles/nginx-php
        #   dockerfile: Dockerfile
        container_name: call
        restart: always
        ports:
            - "6001:6001"
        labels:
            - "environment=production"
            - "traefik.enable=true"
            - "traefik.http.routers.web-2.rule=Host(`call.ucssfcec.work`)"
            - "--entrypoints.web.address=:80"
            - "--entryPoints.ws.address=:6001"
            # - "traefik.http.routers.web-2.entrypoints=websecure"
            # - "traefik.http.routers.web-2.tls.certresolver=myresolver"
        volumes:
            - ~/code/call8:/usr/share/nginx/html:rw
            - ./dockerfiles/sites-available/call.work:/etc/nginx/sites-available/default
            - ~/code/mysql:/var/lib/mysql:rw
          # - ~/code/new-websockets:/usr/share/nginx/html:rw

    mysql:
        container_name: mysql
        image: mysql:5.7
        labels:
            - "environment=production"
            - "traefik.enable=true"
        ports:
          - "${DB_PORT}:3306"
        environment:
          MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
          MYSQL_USER: "${MYSQL_USER}"
          MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - ~/code/mysql:/var/lib/mysql:rw
            # - /var/lib/mysql:/var/lib/mysql
            - ./dockerfiles/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./dockerfiles/mysql/my.cnf:/etc/mysql/my.cnf
