#docker-compose.yml
#https://codigofacilito.com/videos/introduccion-96456894-edd1-43ed-932a-3ccc2d370c3f
#https://stackoverflow.com/questions/63547392/traefik-2-2-docker-websocket-ws-not-working
# TRAEFIK

version: '3'

# Services
services:
    proxy:
        image: traefik:v2.1
        container_name: proxy
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"       # traefik dashboard

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.yml:/traefik.yml
            - ./traefik.log:/traefik.log

    nginx:
        image: nginx
        container_name: nginx
        labels:
            - "environment=dev"
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`traefik.nginx.ucssfcec.xyz`)"

    # web-0:
    #     image: ucssfcec/nginx-php
    #     container_name: nginx-ucssfcec
    #     restart: always
    #     labels:
    #         - "environment=production"
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.web-0.rule=Host(`traefik.ucssfcec.xyz`)"
    #     volumes:
    #         - ~/code/ucssfcec:/usr/share/nginx/html:rw
        # networks:
        #     - stydenet

    web-1:
        image: firma/nginx-php
        # build:
        #   context: ./dockerfiles/nginx-php
        #   dockerfile: Dockerfile
        container_name: nginx-firma
        restart: always
        labels:
            - "environment=production"
            - "traefik.enable=true"
            - "traefik.http.routers.web-1.rule=Host(`traefik.firma.ucssfcec.xyz`)"
        volumes:
          - ~/code/firma:/usr/share/nginx/html:rw
        networks:
            - stydenet

    web-2:
        image: new-websockets/app
        # image: api/nginx-php
        # image: api-websockets/app:latest
        # build:
        #   context: ./dockerfiles/nginx-php
        #   dockerfile: Dockerfile
        container_name: nginx-websockets
        restart: always
        ports:
            - "6001:6001"
        labels:
            - "environment=production"
            - "traefik.enable=true"
            - "traefik.http.routers.web-2.rule=Host(`traefik.websockets.ucssfcec.xyz`)"
            - "--entrypoints.web.address=:80"
            - "--entryPoints.ws.address=:6001"
            # - "traefik.http.routers.web-2.entrypoints=websecure"
            # - "traefik.http.routers.web-2.tls.certresolver=myresolver"
        volumes:
          - ~/code/new-websockets:/var/www/html:rw
          # - ~/code/new-websockets:/usr/share/nginx/html:rw
        networks:
            - stydenet
    node:
        container_name: node
        image: node:9.8
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
         - ~/code/new-websockets:/var/www/html
        networks:
         - stydenet

    mysql:
        container_name: mysql
        image: mysql:5.7
        labels:
            - "environment=production"
            - "traefik.enable=true"
        ports:
          - "${DB_PORT}:3306"
        environment:
          MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
          MYSQL_USER: "${MYSQL_USER}"
          MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
          - /var/lib/mysql:/var/lib/mysql
          - ./dockerfiles/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
          - ./dockerfiles/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
         - stydenet

networks:
    stydenet:
        driver: "bridge"
