#docker-compose.yml
#https://codigofacilito.com/videos/introduccion-96456894-edd1-43ed-932a-3ccc2d370c3f
#https://stackoverflow.com/questions/63547392/traefik-2-2-docker-websocket-ws-not-working
# TRAEFIK

version: '3'

# Services
services:
    proxy:
        image: traefik:v2.1
        container_name: proxy
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"       # traefik dashboard
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.yml:/traefik.yml
            - ./traefik.log:/traefik.log
            - ./letsencrypt:/letsencrypt

    # traefik-certs-dumper:
    #     image: ldez/traefik-certs-dumper:v2.7.4
    #     container_name: traefik-certs-dumper
    #     entrypoint: sh -c '
    #       apk add jq
    #       ; while ! [ -e /data/acme.json ]
    #       || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
    #       sleep 1
    #       ; done
    #       && traefik-certs-dumper file --version v2 --watch
    #       --source /data/acme.json --dest /data/certs'
    #     volumes:
    #       - ./letsencrypt:/data

    # coturn:
    #     image: acaty/coturn
    #     restart: unless-stopped
    #     ports:
    #         - "3478:3478"
    #         - "5349:5349"
    #     container_name: coturn
    #     labels:
    #         - "traefik.enable=true"

    nginx:
        image: nginx
        container_name: nginx
        labels:
            - "environment=dev"
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`nginx.ucssfcec.work`)"

    web-0:
        image: acaty/ucssfcec:1.0.1
        container_name: ucssfcec
        restart: always
        labels:
            - "environment=production"
            - "traefik.enable=true"
            - "traefik.http.routers.web-0.rule=Host(`ucssfcec.work`)"
        volumes:
            - ~/code/ucssfcec:/usr/share/nginx/html:rw
            - ./dockerfiles/sites-available/ucssfcec.work:/etc/nginx/sites-available/default
            # - ~/code/mysql:/var/lib/mysql:rw
            - /var/lib/mysql:/var/lib/mysql

    web-1:
        image: acaty/firma:1.0.2
        container_name: firma
        restart: always
        labels:
            - "environment=production"
            - "traefik.enable=true"
            - "traefik.http.routers.web-1.rule=Host(`firma.ucssfcec.work`)"
        volumes:
            - ~/code/firma:/usr/share/nginx/html:rw
            - ./dockerfiles/sites-available/firma.work:/etc/nginx/sites-available/default
            - ./dockerfiles/php/local.ini:/etc/php/7.3/fpm/conf.d/local.ini
            # - ~/code/mysql:/var/lib/mysql:rw
            - /var/lib/mysql:/var/lib/mysql

    web-2:
        image: acaty/call8:latest
        # image: acaty/call:1.0.0
        container_name: call
        restart: always
        ports:
            - "6001:6001"   # Laravel-websockets
        labels:
            - "environment=production"
            - "traefik.enable=true"
            - "traefik.http.routers.web-2.rule=Host(`call.ucssfcec.work`)"
            - "traefik.http.routers.web-2.entrypoints=web"
            # - "traefik.http.routers.web-2.entrypoints=websecure"
            # - "traefik.http.routers.web-2.tls.certresolver=myresolver"
        volumes:
            - ~/code/call8:/usr/share/nginx/html:rw
            - ./dockerfiles/sites-available/call.work:/etc/nginx/sites-available/default
            # - ~/code/mysql:/var/lib/mysql:rw
            - /var/lib/mysql:/var/lib/mysql
            - ./letsencrypt:/letsencrypt
            # - ./dockerfiles/public/.htaccess:/usr/share/nginx/html/public/.htaccess
            # - ./dockerfiles/public/call8/index.php:/usr/share/nginx/html/public/index.php

    web-3:
        image: acaty/call:1.0.0
        container_name: examen
        restart: always
        labels:
            - "environment=production"
            - "traefik.enable=true"
            - "traefik.http.routers.web-3.rule=Host(`examen.work`)"
            - "traefik.http.routers.web-3.entrypoints=web"
            # - "traefik.http.routers.web-3.entrypoints=websecure"
            # - "traefik.http.routers.web-3.tls.certresolver=myresolver"
        volumes:
            - ~/code/examen:/usr/share/nginx/html:rw
            - ./dockerfiles/sites-available/call.work:/etc/nginx/sites-available/default
            - /var/lib/mysql:/var/lib/mysql
            # - ./letsencrypt:/letsencrypt
            # - ./dockerfiles/public/.htaccess:/usr/share/nginx/html/public/.htaccess
            # - ./dockerfiles/public/call8/index.php:/usr/share/nginx/html/public/index.php

    redis:
        container_name: redis
        image: redis:alpine
        restart: unless-stopped
        tty: true
        labels:
            # - "environment=production"
            - "traefik.enable=true"
        volumes:
            - redisdata:/data

    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: on-failure
        restart: unless-stopped
        labels:
            - "environment=production"
            - "traefik.enable=true"
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            # - ~/code/mysql:/var/lib/mysql:rw
            - /var/lib/mysql:/var/lib/mysql
            - ./dockerfiles/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./dockerfiles/mysql/my.cnf:/etc/mysql/my.cnf

    node:
        container_name: node
        image: node:12.14
        labels:
            - "traefik.enable=true"
        restart: unless-stopped
        tty: true
        working_dir: /usr/share/nginx/html
        # working_dir: /var/www/html
        volumes:
            - ~/code/call8:/usr/share/nginx/html:rw
            # - ~/code/call8:/var/www/html
            # - ~/code/jitsi-laravel:/var/www/html

volumes:
    redisdata:
        driver: "local"