version: '3'

services:
    reverse-proxy:
        image: traefik:v2.1
        container_name: proxy
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
            # - "3478:3478"
            # - "5349:5349"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.yml:/traefik.yml
            - ./traefik.log:/traefik.log
            - ./letsencrypt:/letsencrypt
        # labels:
        #     - "traefik.enable=true"
            # - "traefik.wss.protocol=https"

    # coturn:
    #     image: acaty/coturn:1.0.0
    #     restart: unless-stopped
    #     ports:
    #         - "3478:3478"
    #         - "5349:5349"
    #     container_name: coturn
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.coturn.rule=Host(`turn.ucssfcec.xyz`)"
    #     volumes:
    #         - ./letsencrypt:/letsencrypt

    # traefik-certs-dumper:
    #     image: ldez/traefik-certs-dumper:v2.7.4
    #     container_name: traefik-certs-dumper
    #     entrypoint: sh -c '
    #       apk add jq
    #       ; while ! [ -e /letsencrypt/acme.json ]
    #       || ! [ `jq ".[] | .Certificates | length" /letsencrypt/acme.json` != 0 ]; do
    #       sleep 1
    #       ; done
    #       && traefik-certs-dumper file --version v2 --watch
    #       --source /letsencrypt/acme.json --dest /letsencrypt/certs'
    #     volumes:
    #       - ./letsencrypt:/letsencrypt

    nginx:
        image: nginx
        container_name: nginx
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`disponibilidad.ucssfcec.xyz`)"
            - "traefik.http.routers.nginx.entrypoints=websecure"
            - "traefik.http.routers.nginx.tls.certresolver=myresolver"

    web-0:
        image: acaty/ucssfcec:1.0.1
        container_name: ucssfcec
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web-0.rule=Host(`ucssfcec.xyz`)"
            - "traefik.http.routers.web-0.entrypoints=websecure"
            - "traefik.http.routers.web-0.tls.certresolver=myresolver"
        volumes:
            - ~/code/ucssfcec:/usr/share/nginx/html:rw
            - ./dockerfiles/sites-available/ucssfcec.xyz:/etc/nginx/sites-available/default
            - ~/code/mysql:/var/lib/mysql:rw

    web-1:
        image: acaty/firma:1.0.2
        container_name: firma
        restart: always
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web-1.rule=Host(`firma.ucssfcec.xyz`)"
            - "traefik.http.routers.web-1.entrypoints=websecure"
            - "traefik.http.routers.web-1.tls.certresolver=myresolver"
        volumes:
            - ~/code/firma:/usr/share/nginx/html:rw
            - ./dockerfiles/sites-available/firma.xyz:/etc/nginx/sites-available/default
            - ./dockerfiles/public/.htaccess:/usr/share/nginx/html/public/.htaccess
            - ~/code/mysql:/var/lib/mysql:rw
            - ./dockerfiles/php/local.ini:/etc/php/7.3/fpm/conf.d/local.ini

    web-2:
        image: acaty/call:1.0.0
        # image: acaty/call8:latest
        container_name: call
        restart: always
        ports:
            - "6001:6001"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.web-2.rule=Host(`store.ucssfcec.xyz`)"
            # - "traefik.http.routers.web-2.entrypoints=web"
            - "traefik.http.routers.web-2.entrypoints=websecure"
            - "traefik.http.routers.web-2.tls.certresolver=myresolver"
            # - "traefik.http.routers.web-2.wss.entrypoint=wss"
            # - "--entryPoints.wss.address=wss"
        volumes:
            # - ~/code/jitsi-laravel:/usr/share/nginx/html:rw
            - ~/code/call8:/usr/share/nginx/html:rw
            - ~/code/mysql:/var/lib/mysql:rw
            - ./dockerfiles/sites-available/call.xyz:/etc/nginx/sites-available/default
            - ./dockerfiles/public/.htaccess:/usr/share/nginx/html/public/.htaccess
            - ./dockerfiles/public/index.php:/usr/share/nginx/html/public/index.php
            - ./letsencrypt:/letsencrypt

    node:
        container_name: node
        image: node:12.14
        labels:
            - "traefik.enable=true"
        restart: unless-stopped
        tty: true
        working_dir: /usr/share/nginx/html
        volumes:
            - ~/code/call8:/usr/share/nginx/html:rw
            # - ~/code/firma:/var/www/html
            # - ~/code/jitsi-laravel:/var/www/html

    mysql:
        container_name: mysql
        image: mysql:5.7
        # restart: always
        labels:
            - "traefik.enable=true"
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_ROOT_PASSWORD: "ucss20505378629"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        volumes:
            - ~/code/mysql:/var/lib/mysql:rw
            - ./dockerfiles/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./dockerfiles/mysql/my.cnf:/etc/mysql/my.cnf

