#traefik.yml
#https://codigofacilito.com/videos/introduccion-96456894-edd1-43ed-932a-3ccc2d370c3f
# TRAEFIK

api:
    insecure: true

entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"
    ws:
        address: ":6001"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        # exposedByDefault: true        #### Genera error, no cierra bien el puerto 80 Apache
        exposedByDefault: false
        # constraints: "Label(`environment`, `production`)"
        constraints: "Label(`environment`,`dev`) || Label(`environment`, `production`)  || Label(`environment`, `testing`)"




log:
    filePath: "traefik.log"
    level: ERROR
    format: json
