#traefik.yml
#https://codigofacilito.com/videos/introduccion-96456894-edd1-43ed-932a-3ccc2d370c3f
# TRAEFIK

api:
    insecure: true

entryPoints:
    web:
        address: ":80"
    websecure:
        address: ":443"

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        # constraints: "Label(`environment`, `production`)"
        # constraints: "Label(`environment`,`dev`) || Label(`environment`, `production`)  || Label(`environment`, `testing`)"

# DigitalOcean
# certificatesResolvers:
#     myresolver:
#         acme:
#             email: ana.arashiro@gmail.com
#             storage: /acme.json
#             httpChallenge:
#                 entryPoint: web

log:
    filePath: "traefik.log"
    level: ERROR
    format: json
